### ISSUE TITLE
Create Application Directories

### ISSUE THREAD

**Issue by DBragz** [DBragz/Task-Chain#1]
**User Story:** _As a developer, I want to have a nice and organized repository for each software program so that I can understand and run each part of the Task Chain software._
**Technical Task:** _Create an initial directory, and application, for each application. One for React Native (drewhoek) and the other for Solidity (DBragz) application so that any developer can go into either directory, follow the readme file directions, and get the selected application running with a text output that says "Hello Task Chain Team!"._

**Comment by drewhoek** [comment]
#2 Created new expo app with the welcome message

**Comment by DBragz** [comment]
How do you change the **index** on the top bar @drewhoek?

**Comment by DBragz** [comment]
Pushed mine to [main](https://github.com/DBragz/Task-Chain) as well, test it out when you get a chance a second!
